# Generated by Django 4.2.7 on 2023-11-22 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        default="Tell us something about you",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="Your Mobile", max_length=10, null=True
                    ),
                ),
                (
                    "address1",
                    models.CharField(
                        blank=True, default="Address Line 1", max_length=255, null=True
                    ),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True, default="Address Line 2", max_length=255, null=True
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="Your City", max_length=150, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, default="Your State", max_length=150, null=True
                    ),
                ),
                (
                    "zip",
                    models.CharField(
                        blank=True, default="123456", max_length=6, null=True
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_image1",
                    models.ImageField(blank=True, null=True, upload_to="car_images/"),
                ),
                (
                    "car_image2",
                    models.ImageField(blank=True, null=True, upload_to="car_images/"),
                ),
                (
                    "car_image3",
                    models.ImageField(blank=True, null=True, upload_to="car_images/"),
                ),
                (
                    "car_image4",
                    models.ImageField(blank=True, null=True, upload_to="car_images/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_owner_name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("variant", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("address1", models.CharField(max_length=255)),
                ("address2", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("zip", models.CharField(max_length=10)),
                ("inspection_date", models.DateField()),
                ("message", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
